### ISSUE TITLE
Drop shadow obscures page content

### ISSUE THREAD

**Issue by sebj** [SamReeve96/Acetate-Dissertation-Prototype-#32]
Currently, the drop shadow on Acetate’s sidebar is very large and obscures some page content.

Personally, my suggestion would be to remove the drop shadow and use a 1px separator, as this is less obtrusive and more similar to other web extensions that overlay a sidebar next to a webpage.

**Comment by SamReeve96** [comment]
Good Point, admittedly the drop shadow was just a design placeholder to signify the end of the comments container and the page content being annotated.

I'll look at improving this once I have improved my method of capturing page content.

**Comment by SamReeve96** [comment]
No longer an issue due to card UI changes
