### ISSUE TITLE
Draft annotation style improvements

### ISSUE THREAD

**Issue by SamReeve96** [SamReeve96/Acetate-Dissertation-Prototype-#38]
Draft annotations have a few problems that need to be looked into:
- Drafts cannot be differentiated from normal annotations except from the controls
- Drafts ignore the element order, appearing at the bottom of the list @sebj any thoughts on this?

**Comment by sebj** [comment]
Maybe there should be two tabs at the top of the annotation sidebar – "Annotations" and "Drafts"? I'm assuming all draft annotations are still tied to an element, or some text, as with a 'normal' annotation? How do other tools present draft annotations? Perhaps they could be greyed out slightly.

**Comment by SamReeve96** [comment]
Currently, only a single draft can exist at a time. The draft needs to be saved/confirmed in order to be stored in the browser or database (when implemented) Thus a second tab may not be the best solution here. Greying out the box to indicate that it is a draft seems like a sensible solution.

Any thoughts on the position of the draft in the list of elements? Let know if this is something I should demo to you.

**Comment by sebj** [comment]
Is there a plan to support multiple drafts? As a user, that seems like an odd restriction given other systems with drafts (like email clients) don't have the same restriction.

Maybe drafts could appear first in the annotation list (as they need to be actioned and turned into full annotations first, and so they don't get buried underneath a long list of annotations), but there could be a toggle button to show/hide drafts?

**Comment by SamReeve96** [comment]
Just discussing it with you, I think Draft might be a poor choice of words. Currently a 'Draft' is an annotation that hasn't been stored in chrome storage or sent to the database, and is in an editable state. So if the user were to leave the page, the draft would be lost.

**Comment by sebj** [comment]
Gotcha! So, an unsaved annotation basically. So yeah, I'd show it in the correct order (wherever it's supposed to appear among the other annotations) but greyed out and perhaps with some kind of icon indicator for even more clarity (like a small pencil in one corner).
