### ISSUE TITLE
Annotate button not clear on purpose 

### ISSUE THREAD

**Issue by Et2211** [SamReeve96/Acetate-Dissertation-Prototype-#40]
Might need to include the word 'save' somewhere to make clear

**Comment by SamReeve96** [comment]
Thanks for the feedback, this was originally "saved", however it was suggested to be changed to "annotate" by @sebj

**Comment by sebj** [comment]
I'm not sure what "save" means – will it save the annotation to my computer? Perhaps more user research is required

**Comment by SamReeve96** [comment]
"Annotate" button creates an annotation object, which is stored in the Chrome browser storage and (when implemented, the database) So I argue that "Save" is applicable in that context. 
My argument example would be google drive, where docs are saved not locally but to the cloud, denoted by a message along the lines of "all changes saved in drive"

Perhaps the happy medium here is "Save annotation"? this would be consistent other buttons.

**Comment by sebj** [comment]
As a user, I'm unaware of what Chrome's browser storage is and whether or not you're saving to a database, the cloud or my computer unless that's been fully explained – all I know is that my annotations are stored somewhere.

"Saved" is an adjective that makes sense within the context of your example Google Drive sentence fragment, as most Google Drive users come from desktop computers with file managers and applications that have used 'Save' for 20 years.

For a lot of cloud-based products, "Save" is not used as a verb and is instead replaced with a more simple and direct relevant term – "Comment" (Github), "Tweet" (Twitter), "Post" (Reddit), "New repository" (in Github's add button menu).

Perhaps "Create annotation", "New annotation" or some variant would be more appropriate.

**Comment by Et2211** [comment]
I agree with "save Annotation". Maybe worth having a section on the extension that users can go to find out where and how data is saved to give them peace of mind? Maybe have that info alongside the options?

**Comment by sebj** [comment]
See my above comment (I think we commented at the same time) — "Create annotation" or "New annotation", if not just "Annotate", would be my recommendations.

It's probably best to tell users where their data is being stored, perhaps alongside any options or as part of a user onboarding flow, although there's also the case to be made that as long as the Chrome extension 'just works' perhaps people won't care.

Again, this is something that might be best asked during user research – do people care about where their data is saved? Similarly, how much information about data storage do other Chrome extensions (that are known to use Chrome storage) give?

**Comment by Et2211** [comment]
Any of these suggestions is better than what is currently. I still believe using save is correct term, as it is being saved in your Chrome storage locally, rather than being pushed to any cloud services (@SamReeve96 , correct me if I'm wrong there). How much users care about this will depend on the type of users, are they IT oriented or not

**Comment by sebj** [comment]
Even IT oriented users are unlikely to be aware of where in particular their data is saved (local storage vs Chrome storage vs cloud storage backed by AWS etc.), unless it is explicitly mentioned to them.

I feel like if you were to extend the logic that the user must know everything, the button might as well say "Save new annotation to Chrome synced storage", which is more than likely to completely alienate a large portion of users.

Then again, the best way to find out is with user research conducted on a larger sample size, or live A/B testing of options.

**Comment by shivdhokia** [comment]
I think that there doesn't really need to be a 'Save' or 'Annotate' button. If you've already highlighted the text and selected annotate in the context menu then it seems quite certain that you want an annotation.

**Comment by sebj** [comment]
@shivdhokia Good idea! Perhaps annotations could auto-save as you're typing (or after you stop typing for a second or two).

**Comment by Et2211** [comment]
@shivdhokia @sebj seconded. Great idea

**Comment by SamReeve96** [comment]
Yep, think @shivdhokia hit the nail on the head.

Also, a big fan of Auto-saving as the User types the comment, I think the way this will be implemented is:
- The user creates an annotation via right-click (Context menu)
- A popup appears, allowing the user to edit the annotation comment.
- The annotation is automatically saved as the user types to the local cache instance (Chrome sync storage)
- Then at intervals, the cached instance is checked against the remote instance and any changes are synced

Thanks All! @Et2211 @Sebj and @shivdhokia
